// Thin typed wrapper around the wasm tokenizer.
// The `./wasm/` directory is generated by `yarn build:wasm` and is gitignored.
import init, {
  import_playlist_songs_wasm,
  import_song_wasm,
  version,
} from "./wasm/ireal_tokenizer.js";
import type { ImportedPlaylist, ImportedSong } from "./types";

let ready: Promise<unknown> | null = null;

/** Initialize the wasm module once (idempotent). */
export function initTokenizer(): Promise<unknown> {
  if (!ready) ready = init();
  return ready;
}

/** Parse an `irealb://` playlist URL into its title + fully parsed songs. */
export async function importPlaylist(url: string): Promise<ImportedPlaylist> {
  await initTokenizer();
  return JSON.parse(import_playlist_songs_wasm(url)) as ImportedPlaylist;
}

/** Parse a single `=`-delimited iReal song link. */
export async function importSong(link: string): Promise<ImportedSong> {
  await initTokenizer();
  return JSON.parse(import_song_wasm(link)) as ImportedSong;
}

export async function tokenizerVersion(): Promise<string> {
  await initTokenizer();
  return version();
}
